### ISSUE TITLE
error importing pycuda

### ISSUE THREAD

**Issue by AnyMail197** [droyed/eucl_dist#5]
Hi, 
I have cuda11.1 installed on windows 10
and i have installed pycuda-2020.1-py3.6

this error showed for me.
Any suggestions?

Traceback (most recent call last):
  File "C:/Users/s-f2/Desktop/DELF/gpu_euclidean/main.py", line 4, in <module>
    from eucl_dist.gpu_dist import dist as gdist
  File "C:\Users\s-f2\Desktop\DELF\gpu_euclidean\eucl_dist\gpu_dist.py", line 1, in <module>
    import pycuda.gpuarray as gpuarray
  File "C:\Users\s-f2\Desktop\DELF\gpu_euclidean\venv\lib\site-packages\pycuda\gpuarray.py", line 4, in <module>
    import pycuda.elementwise as elementwise
  File "C:\Users\s-f2\Desktop\DELF\gpu_euclidean\venv\lib\site-packages\pycuda\elementwise.py", line 35, in <module>
    from pycuda.tools import context_dependent_memoize
  File "C:\Users\s-f2\Desktop\DELF\gpu_euclidean\venv\lib\site-packages\pycuda\tools.py", line 34, in <module>
    import pycuda.driver as cuda
  File "C:\Users\s-f2\Desktop\DELF\gpu_euclidean\venv\lib\site-packages\pycuda\driver.py", line 62, in <module>
    from pycuda._driver import *  # noqa
ImportError: DLL load failed: The specified procedure could not be found.

Process finished with exit code 1

**Comment by droyed** [comment]
Does "import pycuda" work? If not, that shows pycuda is not properly installed, else we have a real issue.

**Comment by AnyMail197** [comment]
yes it works
what then is the problem?

**Comment by AnyMail197** [comment]
I got the problem
the compute capability of my graphic card is too low.
